---
title: "bartel_miRNAs.Rmd"
author: "Pierre-Luc Germain"
date: "1/29/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

suppressPackageStartupMessages({
  library(SummarizedExperiment)
  library(edgeR)
  library(SEtools)
  library(BiocParallel)
  library(sva)
  library(RColorBrewer)
})
```

```{r colors}

# colors
ancols <- list(day=c("0"="#3F3F3F",
                        "9" ="#575757",
                        "15" ="#707070",
                        "21" = "#898989",
                        "27" ="#A1A1A1",
                        "33" ="#BABABA",
                        "40" = "#D3D3D3" 
                        ) )
  
heatcol = colorRampPalette(c("#31a354", "white", "#3182bd"))(100)
heatcol2 = colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(100)
#heatcol3 = inferno(256)
annocolramp = colorRampPalette(c("#3F3F3F","#D3D3D3"))(7)
```

## PCA

```{r load bartel, warning=FALSE, message=FALSE}

# load bartel SE object
setwd("/mnt/schratt/enrichMir_datasets/")
se <- readRDS("R/symbols.SE.rds")
```

```{r process bartel, warning=FALSE, message=FALSE}

# get logcpm values & factorize Batch info
assays(se)$logcpm <- log1p(cpm(calcNormFactors(DGEList(assay(se)))))
se$Batch <- factor(se$Batch)

# separate the 2 cell lines
se.hela <- se[,se$Cell_Line=="HeLa"]
se.hela <- se.hela[rowSums(assay(se.hela)>=10)>1,]
se.hek <- se[,se$Cell_Line!="HeLa"]
se.hek <- se.hek[rowSums(assay(se.hek)>=10)>1,]
```

```{r pca bartel, warning=FALSE, message=FALSE}

# plot PCA

## combined
plgINS::plPCA(assays(se)$logcpm, as.data.frame(colData(se)), colorBy = "Cell_Line", 
              add.labels = FALSE, annotation_columns = colnames(colData(se))[1:3])

## HeLa 
p.hela <- plgINS::plPCA(assays(se.hela)$logcpm, as.data.frame(colData(se.hela)), 
                   colorBy = "miRNA", shapeBy = "Batch", add.labels = FALSE, 
                   annotation_columns = colnames(colData(se.hela))[1:3])
add_markers(p.hela, color = ~se.hela$miRNA, colors = "Paired")

## HeLa batch effect
plgINS::plPCA(assays(se.hela)$logcpm, as.data.frame(colData(se.hela)), colorBy = "Batch",
              add.labels = FALSE, annotation_columns = colnames(colData(se.hela))[1:3])

## HEK
p.hek <- plgINS::plPCA(assays(se.hek)$logcpm, as.data.frame(colData(se.hek)), 
                       colorBy = "miRNA", shapeBy = "Batch", add.labels = FALSE,
                       annotation_columns = colnames(colData(se.hek))[1:3])
add_markers(p.hek, color = ~se.hek$miRNA, colors = "Paired")

## HEK batch effect
plgINS::plPCA(assays(se.hek)$logcpm, as.data.frame(colData(se.hek)), colorBy = "Batch", 
              add.labels = FALSE, annotation_columns = colnames(colData(se.hek))[1:3])
```

## DEA

### HeLa

```{r hela dea bartel}

se.hela$miRNA <- droplevels(se.hela$miRNA)

# correct data for batch effect (for visualization)
assays(se.hela)$corrected <- ComBat(assays(se.hela)$logcpm, batch = se.hela$Batch, 
                                    model.matrix(~se.hela$miRNA))

# generate a 'control' sample out of the median normalized counts over all samples
e.ctrl <- sapply(unique(se.hela$Batch), ls=min(colSums(assay(se.hela))), FUN=function(x,ls){
  rowMedians(exp(assays(se.hela)$logcpm[,se.hela$Batch==x])-1)*ls/1000000
})
# add control sample to SE colData with
dd <- rbind(colData(se.hela)[,c("Batch","miRNA")], data.frame(Batch=unique(se.hela$Batch), 
                                                              miRNA="CTRL"))
dd$miRNA <- relevel(dd$miRNA, "CTRL")

# add 'control' sample counts to SE sample counts
dds <- DGEList(cbind(assay(se.hela), e.ctrl))

# do DEA taking batch effect into account
dds <- calcNormFactors(dds)
mm <- model.matrix(~Batch+miRNA, data=dd)
dds <- estimateDisp(dds,mm)
fit <- glmFit(dds,mm)
## fit linear model dropping one sample at a time (using multiple cores)
dea.list.hela <- bplapply( levels(dd$miRNA)[-1], BPPARAM=MulticoreParam(8), FUN=function(x){
  as.data.frame(topTags(glmLRT(fit, paste0("miRNA",x)),Inf))
})
names(dea.list.hela) <- levels(dd$miRNA)[-1]
```

```{r export hela bartel}

# export
saveRDS(dea.list.hela, "~/master_19_20/enrichMiR_benchmark/bartel_HeLa.deaList.rds")
```

```{r import hela bartel}

# import
dea.list.hela <- readRDS("~/master_19_20/enrichMiR_benchmark/bartel_HeLa.deaList.rds")
```

### HEK

```{r hek dea bartel}

se.hek$miRNA <- droplevels(se.hek$miRNA)
se.hek$Batch <- droplevels(se.hek$Batch)

# correct data for batch effect (for visualization)
assays(se.hek)$corrected <- ComBat(assays(se.hek)$logcpm, batch = se.hek$Batch, 
                                    model.matrix(~se.hek$miRNA))

# generate a 'control' sample out of the median normalized counts over all samples
e.ctrl2 <- sapply(unique(se.hek$Batch), ls=min(colSums(assay(se.hek))), FUN=function(x,ls){
  rowMedians(exp(assays(se.hek)$logcpm[,se.hek$Batch==x])-1)*ls/1000000
})
# add control sample to SE colData with
dd2 <- rbind(colData(se.hek)[,c("Batch","miRNA")], data.frame(Batch=unique(se.hek$Batch), 
                                                              miRNA="CTRL"))
dd2$miRNA <- relevel(dd2$miRNA, "CTRL")

# add 'control' sample counts to SE sample counts
dds2 <- DGEList(cbind(assay(se.hek), e.ctrl2))

# do DEA taking batch effect into account
dds2 <- calcNormFactors(dds2)
mm2 <- model.matrix(~Batch+miRNA, data=dd2)
dds2 <- estimateDisp(dds2,mm2)
fit2 <- glmFit(dds2,mm2)
## fit linear model dropping one sample at a time (using multiple cores)
dea.list.hek <- bplapply( levels(dd2$miRNA)[-1], BPPARAM=MulticoreParam(8), FUN=function(x){
  as.data.frame(topTags(glmLRT(fit2, paste0("miRNA",x)),Inf))
})
names(dea.list.hek) <- levels(dd2$miRNA)[-1]
```

```{r export hek bartel}

# export
saveRDS(dea.list.hek, "~/master_19_20/enrichMiR_benchmark/bartel_HEK.deaList.rds")
```

```{r import hek bartel}

# import
dea.list.hek <- readRDS("~/master_19_20/enrichMiR_benchmark/bartel_HEK.deaList.rds")
```


### HEK no batch correction

```{r hek no batch dea bartel}

# do DEA not taking batch effect into account
mm3 <- model.matrix(~1+miRNA, data=dd2)
dds3 <- estimateDisp(dds2,mm3)
fit3 <- glmFit(dds3,mm3)
## fit linear model dropping one sample at a time (using multiple cores)
dea.list.hek_nb <- bplapply( levels(dd2$miRNA)[-1], BPPARAM=MulticoreParam(8), FUN=function(x){
  as.data.frame(topTags(glmLRT(fit3, paste0("miRNA",x)),Inf))
})
names(dea.list.hek_nb) <- levels(dd2$miRNA)[-1]
```

```{r export hek no batch bartel}

# export
saveRDS(dea.list.hek_nb, "~/master_19_20/enrichMiR_benchmark/bartel_HEK_noBatch.deaList.rds")
```

```{r import hek no batch bartel}

# import
dea.list.hek_nb <- readRDS("~/master_19_20/enrichMiR_benchmark/bartel_HEK_noBatch.deaList.rds")
```

## HMs

```{r sig tx changes bartel}

# select significant gene expression changes
degs.hela <- lapply(dea.list.hela, FUN=function(x) row.names(x)[x$FDR<0.05])
degs.hek <- lapply(dea.list.hek, FUN=function(x) row.names(x)[x$FDR<0.05])
degs.hek_nb <- lapply(dea.list.hek_nb, FUN=function(x) row.names(x)[x$FDR<0.05])
# number of significant gene expression changes per sample
## HeLa
lapply(degs.hela,length)
## HEK
lapply(degs.hek,length)
## HEK no batch correction
lapply(degs.hek_nb,length)
```

```{r hek comparison bartel}

# comparison of HEK DEA with and without batch effect taken into account
## median number of significant changes: HEK w batch
median(unlist(lapply(degs.hek,length)))
## median number of significant changes: HEk w/out batch
median(unlist(lapply(degs.hek_nb,length)))

t(sapply(levels(se.hek$miRNA), FUN = function(x){
  b_in_nb <- sum(degs.hek[[x]] %in% degs.hek_nb[[x]])/length(degs.hek[[x]])
  nb_in_b <- sum(degs.hek_nb[[x]] %in% degs.hek[[x]])/length(degs.hek_nb[[x]])
  c(b_in_nb=b_in_nb, nb_in_b=nb_in_b)
}))

```

```{r hm bartel}

# heatmaps

## HeLa logcpm
sehm(se.hela[,order(se.hela$miRNA)], degs.hela$`miR-143`, do.scale = TRUE, 
     anno_columns = c("miRNA","Batch"), assayName = "logcpm", 
     show_rownames = FALSE, anno_colors = ancols)

## HeLa logcpm batch corrected
sehm(se.hela[,order(se.hela$miRNA)], degs.hela$`miR-143`, do.scale = TRUE, 
     anno_columns = c("miRNA","Batch"), assayName = "corrected", 
     show_rownames = FALSE, anno_colors = ancols)

## HEK logcpm
sehm(se.hek[,order(se.hek$miRNA)], degs.hek$`miR-184`, do.scale = TRUE, 
     anno_columns = c("miRNA","Batch"), assayName = "logcpm", 
     show_rownames = FALSE, anno_colors = ancols)

## HEK logcpm batch corrected
sehm(se.hek[,order(se.hek$miRNA)], degs.hek$`miR-184`, do.scale = TRUE, 
     anno_columns = c("miRNA","Batch"), assayName = "corrected", 
     show_rownames = FALSE, anno_colors = ancols)
```