---
title: "Diluted benchmark datasets"
author: "Pierre-Luc Germain"
date: "`r Sys.Date()`"
output: html_document
---

# creating the diluted datasets

```{r}
deas <- list( HEK=readRDS("bartel_HEK.deaList.rds"),
              Hela=readRDS("bartel_HeLa.deaList.rds") )
deas <- unlist(deas, recursive = FALSE)

names(i) <- i <- 1:5
props <- unlist(lapply( c("20"=0.2, "30"=0.3, "40"=0.4, "50"=0.5), 
                        FUN=function(x) lapply(i, FUN=function(y) x)))
set.seed(1234)
deas2 <- unlist(lapply(deas, FUN=function(x){
  x <- plgINS::dround(x[,-3], roundGreaterThan1 = TRUE)
  lapply(props, FUN=function(p){
    sn <- floor(p*nrow(x))
    i <- sample(seq_len(nrow(x)), sn)
    j <- sample(seq_len(sn),seq_len(sn))
    row.names(x)[i] <- row.names(x)[i[j]]
    x
  })
}), recursive=FALSE)
saveRDS(deas2, file="dilutedDatasets.rds")
```


# Benchmarking

We'll take the first dea, run enrichmir, and benchmark it:

```{r}
devtools::load_all("../enrichMiR/")
TS <- readRDS("data/TargetScan_all.rds")
fams <- metadata(TS)$families

dea <- deas[[1]]
e <- enrichMiR(dea, TS)

TP <- unique(as.character(fams[grep("miR-122$|miR-122-",names(fams))]))
thresholds <- c(0,10^(-10:-3),0.005,0.01,0.025,0.05,0.075,0.1,0.15,0.2,0.25,0.3,0.5)

dat <- dplyr::bind_rows(lapply(e@res, FUN=function(x){
  if("family" %in% colnames(x)) row.names(x) <- x$family
  x$truth <- row.names(x) %in% TP
  x$FDR[is.na(x$FDR)] <- 1
  as.data.frame(t(sapply(thresholds, FUN=function(i){
    P <- sum(x$FDR<=i)
    c( threshold=i,
       P=P,
       TP=sum(x$FDR<=i & x$truth),
       FP=sum(x$FDR<=i & !x$truth),
       TPR=sum(x$FDR<=i & x$truth)/sum(x$truth),
       FPR=sum(x$FDR<=i & !x$truth)/sum(!x$truth),
       FDR=ifelse(P>0,sum(x$FDR<=i & !x$truth)/P,0) )
  })))
}), .id="method")

ggplot(dat, aes(FPR, TPR, colour=method)) + geom_line() + geom_point(size=3) + 
  scale_x_log10()  + scale_colour_manual(values=cols)


doBenchmark <- function(res, TP){
  res <- lapply(res, FUN=function(x){
    if("family" %in% colnames(x)) row.names(x) <- x$family
    x$truth <- row.names(x) %in% TP
    x$FDR[is.na(x$FDR)] <- 1
    x
  })
  data.frame( method=names(res),
              detPPV=sapply(res, FUN=function(x) 1/which(x$truth)[1] ),
              log10QRatio=sapply(res, FUN=function(x){
                tp1 <- -log10(x$FDR[which(x$truth)[1]])
                fp1 <- -log10(x$FDR[which(!x$truth)[1]])
                tp1-fp1-(min(tp1,fp1))
              }),
              log10QrelIncrease=sapply(res, FUN=function(x){
                tp1 <- -log10(x$FDR[which(x$truth)[1]])
                fp1 <- -log10(x$FDR[which(!x$truth)[1]])
                (tp1-fp1)/(min(tp1,fp1))
              }))
  
}
```


