---
title: "enrichMiR benchmark results"
author: "tgermade"
date: "`r Sys.Date()`"
output:
    html_document:
        toc: true
        toc_float: true
        theme: 'cerulean'
        highlight: 'tango'
        df_print: paged
---

<style>
  .main-container {
    max-width: 1500px !important;
  }
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE, warning=FALSE}
suppressPackageStartupMessages({
  library(ggplot2)
  library(plgINS)
  library(DT)
  library(viridis)
  library(RColorBrewer)
  library(data.table)
  library(dplyr)
  library(cowplot)
  library(matrixStats)
  library(RUVSeq)
})
```

## Allocation

```{r allocation}

# input file: Bartel DEA SE
input <- list(
  hek="/mnt/schratt/enrichMiR_benchmark/results/bartel.hek.benchmark.rds",
  hek.exon="/mnt/schratt/enrichMiR_benchmark/results/bartel.hek.exon.benchmark.rds",
  hela="/mnt/schratt/enrichMiR_benchmark/results/bartel.hela.benchmark.rds",
  hela.exon="/mnt/schratt/enrichMiR_benchmark/results/bartel.hela.exon.benchmark.rds",
  jeong="/mnt/schratt/enrichMiR_benchmark/results/jeong.benchmark.rds",
  jeong.exon="/mnt/schratt/enrichMiR_benchmark/results/jeong.exon.benchmark.rds",
  rat="/mnt/schratt/enrichMiR_benchmark/results/ratPolyA.benchmark.rds",
  rat.exon="/mnt/schratt/enrichMiR_benchmark/results/ratPolyA.exon.benchmark.rds")
```

## Loading

```{r load}

# import dataframes
test <- lapply(input,readRDS)
# combine dataframes
test2 <- do.call("rbind", test)
test2$dataset <- sapply(strsplit(rownames(test2),"\\."), function(x) paste(rev(rev(x)[-1]),collapse="."))
```

```{r}

test <- split(df.all, df.all$dataset)
df <- test$bartel.hek
dea.names <- as.character(unique(df$treatment))
props.all <- levels(df$prop)
```

# Plots

```{r plot scores, message=FALSE, warning=FALSE, eval=TRUE, fig.width=12, fig.height=6}

# plots
for(i in c("detPPV","FP.atFDR05","log10QDiff","TP.atFDR05")){
  cat("Score analysis: ", i,"\n\n")
  ## boxplot
  # print( 
  #   ggplot(df, aes(x=prop, y=df[[i]], fill=method)) + geom_boxplot() + ylab(i) 
  #   )
  if(i!="TP.atFDR05"){
    ## density plot: score distribution per permutation
    print( 
      ggplot(df, aes(log10(df[[i]]))) + geom_density(aes(fill=method), alpha=0.9)  + facet_wrap(~prop) + xlab(i)
      )
    ## violin plot
    if(!i %in% c("FP.atFDR05","log10QDiff")){
      print( 
        ggplot(df, aes(x=prop, y=df[[i]], fill=method))  + geom_violin() + facet_wrap(~method) +
          guides(fill=FALSE) + ylab(i) + geom_jitter(shape=16, position=position_jitter(0.2))
      )
    }
  }
  ## boxplot FP
  if(i=="FP.atFDR05"){
    print(
      ggplot(df, aes(x=method, y=df[[i]], fill=method)) + geom_boxplot() +
            guides(fill=FALSE) + ylab(i) + coord_flip() + scale_x_discrete(limits = rev(levels(df$method)))
          )
  }
  ## violin plot median
 print(
   ggplot(df, aes(x=prop, y=df[[i]], fill=method))  + geom_violin(draw_quantiles = 0.5) + facet_wrap(~method) +
    guides(fill=FALSE) + ylab(i)
  ) 
  ## mean curves plot
  if(i!="FP.atFDR05"){
    print(
      ggplot(df, aes(x=as.integer(df$prop), y=df[[i]], color=method)) + geom_smooth(alpha=.1) + scale_x_continuous(labels=unique(props.all)) + 
        ylab(i) + xlab("prop")
      )
  }
}
```

```{r fp-tp plot, message=FALSE, warning=FALSE, eval=TRUE, fig.width=12, fig.height=8}

# FP-TP plot (at FDR .05)
## get average number of FP & TP at FDR .05 for each combination of permutation & method
df.agg <- aggregate(df[,c("FP.atFDR05","TP.atFDR05")], by=df[,c("prop","method")], FUN=mean)
## plot
ggplot(df.agg, aes(x=FP.atFDR05, y=TP.atFDR05, color=method, shape=prop, group=method)) + geom_line() + geom_point(size=3) + 
  geom_label(data=df.agg %>% filter(prop==50), aes(label=method), position=position_jitter(width=3,height=.03))


# ggplot(df.agg, aes(x=FP.atFDR05, y=TP.atFDR05, color=method, shape=prop, group=method)) + geom_line() + geom_point(size=3) + 
# geom_label(data=df.agg %>% filter(prop==50),
#     aes(label=method),
#     nudge_x = 0.5, nudge_y = 0.1, 
#     check_overlap = T
#   )

library(ggrepel)
ggplot(df.agg, aes(x=FP.atFDR05, y=TP.atFDR05, color=method, shape=prop, group=method)) + 
  geom_line() + 
  geom_point(size=3) + 
  geom_label_repel(data=df.agg %>% filter(prop==50), 
                  aes(label=method), 
                  force=5, 
                  segment.color="black",
                  segment.alpha=.4, 
                  arrow=arrow(length = unit(.01,"npc"), type = "open", ends = "last")
                  ) +
  geom_point() +
  theme_classic(base_size = 15)
```

### scores over the datasets

```{r overview mean datasets, message=FALSE, warning=FALSE, eval=TRUE, fig.width=12, fig.height=6}

# mean scores over all datasets; this shows which datasets were difficult to handle for the tests
ggplot(df, aes(x=prop, y=detPPV, fill=treatment))  + geom_violin(draw_quantiles = 0.5) + facet_wrap(~treatment) +
      guides(fill=FALSE)

mean.datasets <- lapply( unique(df$treatment), FUN=function(x) 
  sapply( unique(df$prop), function(y) 
    round( mean(df$detPPV[df$treatment==x & df$prop==y], na.rm=TRUE), 3) 
    )
  )
names(mean.datasets) <- dea.names
for(i in dea.names){
  names(mean.datasets[[i]]) <- unique(df$prop)
}
mean.datasets
```

### scores over methods

```{r overview mean methods, message=FALSE, warning=FALSE, eval=TRUE, fig.width=12, fig.height=6}

# mean scores over all methods
ggplot(df, aes(x=prop, y=detPPV, fill=method))  + geom_violin(draw_quantiles = 0.5) + facet_wrap(~method) +
      guides(fill=FALSE)

mean.methods <- lapply( unique(df$method), FUN=function(x) 
  sapply( unique(df$prop), function(y) 
    round( mean(df$detPPV[df$method==x & df$prop==y], na.rm=TRUE), 3)
    )
  )
names(mean.methods) <- unique(df$method)
for(i in unique(df$method)){
  names(mean.methods[[i]]) <- unique(df$prop)
}
mean.methods
```

### TP ratio at FDR 0.05 over methods

```{r overview sensitivity methods, message=FALSE, warning=FALSE, eval=TRUE, fig.width=12, fig.height=6}

# sensitivity score (ratio of TP at FDR 0.05)
sens.methods <- lapply( unique(df$method), FUN=function(x) 
  sapply( unique(df$prop), function(y)
    round( sum(df$TP.atFDR05==1 & df$method==x & df$prop==y) / sum(df$method==x & df$prop==y), 3)
    )
  )
names(sens.methods) <- unique(df$method)
for(i in unique(df$method)){
  names(sens.methods[[i]]) <- unique(df$prop)
}
sens.methods
```