---
title: "miRNA expression histograms"
author: "tgermade"
date: "`r Sys.Date()`"
output:
    html_document:
        toc: true
        toc_float: true
        theme: 'cerulean'
        highlight: 'tango'
        df_print: paged
---

<style>
  .main-container {
    max-width: 1500px !important;
  }
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE, warning=FALSE}
suppressPackageStartupMessages({
  library(SummarizedExperiment)
  library(ggplot2)
  library(plgINS)
  library(DT)
  library(viridis)
  library(RColorBrewer)
  library(data.table)
  library(dplyr)
  library(cowplot)
  library(matrixStats)
  library(RUVSeq)
  library(microRNAome)
})
```



```{r load}
data("microRNAome")
se <- readRDS("/mnt/schratt/tgermade_test/master_19_20/iPSCdiff/data/Small_RNA/smallRNA_oasis.DEA.SE.rds")
```

```{r prep function}
generateDF <- function(assay){
  l <- lapply(1:ncol(assay), function(i) data.frame(counts=assay[assay[,i]>0,i],mirna=rownames(assay)[assay[,i]>0],dataset=as.factor(i)))
  return(do.call(rbind.data.frame, l))
}
```

```{r prep}
hela <- generateDF(assay(microRNAome)[,microRNAome$cell_tissue=="hela"])
hek <- generateDF(assay(microRNAome)[,microRNAome$cell_tissue=="hek293"])
ipsc <- generateDF(assays(se)$counts)
```

```{r hist function}
histoPlots <- function(df){
  if(length(levels(df$dataset))>5){
      df1 <- df[as.numeric(as.character(df$dataset)) <= ceiling(max(as.numeric(as.character(df$dataset)))/2),]
      df2 <- df[as.numeric(as.character(df$dataset)) > max(as.numeric(as.character(df1$dataset))),]
      print(
        ggplot(df1, aes(log1p(df1$counts))) + geom_density(aes(fill=rev(dataset)),bw=.12,alpha=0.5) + 
          geom_vline(xintercept = c(log1p(3),log1p(10)))
      )
      print(
        ggplot(df2, aes(log1p(df2$counts))) + geom_density(aes(fill=rev(dataset)),bw=.12,alpha=0.5) + 
          geom_vline(xintercept = c(log1p(3),log1p(10)))
      )
  } else {
    print(
      ggplot(df, aes(log1p(df$counts))) + geom_density(aes(fill=rev(dataset)),bw=.12,alpha=0.7) + geom_vline(xintercept = c(log1p(3),log1p(10)))
    )
  }
  print(
    ggplot(df, aes(df$counts)) + geom_density(aes(fill=dataset),bw=.8,alpha=0.5) + geom_vline(xintercept = c(3,10)) + facet_wrap(~dataset) + xlim(range(1,40))
  )
}
```

```{r hist 1, message=FALSE, warning=FALSE, eval=TRUE, fig.width=12, fig.height=6}
histoPlots(hela)
```

```{r hist 2, message=FALSE, warning=FALSE, eval=TRUE, fig.width=12}
histoPlots(hek)
```

```{r hist 3, message=FALSE, warning=FALSE, eval=TRUE, fig.width=12, fig.height=7}
histoPlots(ipsc)
```








